global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.209.21.212:9090']
        labels:
          instance: prometheus

  - job_name: nodeExporter
    static_configs:
      - targets: ['10.209.21.212:9100']

  - job_name: springboot
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.209.21.212:8080']

